### ISSUE TITLE
getQuiz,  getConnections, getWordGames

### ISSUE THREAD

**Issue by royankit11** [arinashah30/Cultured#91]
Given the name of the activity, get that activity from Firebase. Make a new model of that activity with the information retrieved from the database, and return that model. 

getQuiz(String: name) -> Quiz {
  //get quiz information from database
 //Create new Quiz object with that information
 //Return that object
}

Do this for Quizzes, Connections and WordGames

**Comment by Connor-1233** [comment]
- [ ] getQuiz
- [ ] getConnections
- [ ] getWordGames
